name: Flatpak Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: yafi-${{ github.sha }}.flatpak
        manifest-path: au.stevetech.yafi.json
